config/routes.rb
Rails.application.routes.draw do

  resources :book_histories
  get 'homes/new'
  get 'homes/show' => 'homes#show', as: :home
  get 'sessions/signup' => 'sessions#signup', :as => :signup
  post 'sessions/new_user' => 'sessions#new_user'
  root :to => 'sessions#new'
  get    'login'   => 'sessions#new', :as => :loginpage
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

   get 'books/:id/borrow' => 'books#borrow', :as => :borrow_book
   get 'book_histories/:data/index' => 'book_histories#index', :as =>:check_user_history
   get 'books/:id/request' => 'books#request_book', :as => :request_book
   get 'books/:id/return' => 'books#return', :as => :return_book
   get 'books/:id/cancel_request' => 'books#cancel_request', :as => :cancel_request_book
  resources :searches
  resources :books
  resources :users

  match ':controller(/:action(/:id))', :via=> :get

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :books
  has_many :book_histories
  before_save { self.email = email.downcase } 
  validates :name, 
            :presence => {:message => "Wpisz imię"},
            :length => {:maximum => 255}
  validates :email,
            :presence => {:message => "Wpisz email"},
            :uniqueness => {:message => "Email już istnieje"},
            :email_format => {:message => "Email jest nie prawidłowy"},
            :length => {:maximum => 255}
  validates :address,
            :length => {:maximum => 255}
  validates :phone,
            :length => {:minimum => 9, :maximum => 9},
            :numericality => {:only_integer => true }
  has_secure_password
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy] 
  # GET /users
  # GET /users.json
  def index
    @users = User.all.paginate(:per_page=>10, :page=>params[:page])
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'Użytkownik został utworzony.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'Szczegóły profilu zostały zaktualizowane.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    user_books = Book.find_by(user_id: @user.id)
      if user_books == nil
        @user.destroy
        flash[:notice] = "Użytkownik został usunięty."
        redirect_to users_url
      else
        flash[:danger] = "Użytkownik ma zarezerwowaną książkę, więc nie można go usunąć."
        redirect_to users_url
      end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :address, :phone, :is_admin, :is_deleted)
    end
  end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> Użytkownik został zablokowany:</h2>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "Imię" %><br>
    <%= f.text_field :name, class: "form-control"%>
  </div>
  <div class="field">
    <%= f.label :password, "Hasło" %><br>
    <%= f.password_field :password, class: "form-control"%>
  </div>
  <div class=" input-group">
    <%= f.label :email %><br>
    <%= f.text_field :email,class: "form-control"%>
  </div>
  <div class="field">
    <%= f.label :address, "Adres" %><br>
    <%= f.text_field :address, class: "form-control"%>
  </div>
  <div class="field">
    <%= f.label :phone, "Numer telefonu" %><br>
    <%= f.text_field :phone, class: "form-control"%>
  </div>
  <div class="field">
    <%= f.label :is_admin, "Administrator?" %><br>
    <%= f.check_box :is_admin %>
  </div>
  <div class="actions">
    <%= f.submit 'Dodaj', :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/users/_form_edit.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> Użytkownik został zablokowany:</h2>
      <ul>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, "Imię" %><br>
    <%= f.text_field :name, class: "form-control", placeholder: "Imię" %>
  </div>
  <div class="form-group">
    <%= f.label :email %><br>
    <%= f.text_field :email, class: "form-control", placeholder: "Email" %>
  </div>
  <div class="form-group">
    <%= f.label :address, "Adres" %><br>
    <%= f.text_field :address, class: "form-control", placeholder: "Adres" %>
  </div>
  <div class="form-group">
    <%= f.label :phone, "Telefon" %><br>
    <%= f.text_field :phone, class: "form-control", placeholder: "Numer telefonu" %>
  </div>
  <div class="form-group">
    <%= f.submit 'Zastosuj', :class => "btn btn-success" %>
  </div>
<% end %>

app/views/users/_form_password.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> Użytkownik został zablokowany:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="field">
    <%= f.label :password, "Hasło" %><br>
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit, "Zastosuj" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div style="padding:15px 50px 15px 50px">
<% if @current_user.is_admin? %>
<h3>Edycja profilu</h3>

<%= render 'form_edit' %>
<%else%>
<blockquote>
  <p class="text-danger">Nie masz wystarczających uprawnień do podglądu tej strony</p>
</blockquote>
<% end %>
</div>

app/views/users/edit_password.html.erb
<h1>Edycja użytkownika</h1>

<%= render 'form_password' %>

<%= link_to 'Powrót', users_path %>

app/views/users/index.html.erb
<div style="margin:0 auto; left:0px; padding:5px 45px 5px 45px">
<% if @current_user.is_admin? %>
<p id="notice"><%= notice %></p>

<h3>Lista użytkowników</h3>

<table class="table table-hover table-responsive">
  <thead>
    <tr style="background-color:#D5DBDB">
      <th>Imię</th>
      <th>Email</th>
      <th>Adres</th>
      <th>Telefon</th>
      <th>Administrator</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.address %></td>
        <td><%= user.phone %></td>
        <td><%= user.is_admin %></td>
        <td><%= link_to 'Pokaż', user, class: "btn btn-success", :style => "color: #ffffff"%></td>
        <td><%= link_to 'Edytuj', edit_user_path(user), class: "btn btn-warning" , :style => "color: #ffffff"%></td>
        <td><%=link_to 'Pokaż historię rezerwacji', check_user_history_path(:data => {:user_id => user.id, :book_id => nil}), :class => "btn btn-success", :style => "color: #ffffff"%></td>
        <%if user.id != @current_user.id %>
        <td><%= link_to 'Usuń', user, method: :delete, data: { confirm: 'Czy jesteś pewien?' }, class: "btn btn-danger" , :style => "color: #ffffff"%></td>

        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @users%>
<br>

<%= link_to 'Dodaj nowego użytkownika', new_user_path, class: "btn btn-primary", style: "color: #ffffff" %>
<%else%>
<blockquote>
  <p class="text-danger">Nie masz wystarczających uprawnień do podglądu tej strony</p>
</blockquote>
<% end %>
</div>

app/views/users/new.html.erb
<div style="margin:0 auto; left:0px; padding:5px 75px 5px 75px">
<% if @current_user.is_admin? %>

    <h3>Nowy użytkownik</h3>

    <%= render 'form' %>
<%else%>
    <blockquote>
      <p class="text-danger">Nie masz wystarczających uprawnień do podglądu tej strony</p>
    </blockquote>
<%end%>
</div>

app/views/users/show.html.erb
<div style="margin:0 auto; left:0px; padding:5px 75px 5px 75px">
<%if (@user.id == @current_user.id) || @current_user.is_admin %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Imię:</strong>
  <%= @user.name %>
</p>
<p>
<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Adres:</strong>
  <%= @user.address %>
</p>

<p>
  <strong>Telefon:</strong>
  <%= @user.phone %>
</p>
<br/><br>
<%= link_to 'Powrót', users_path, :class => "btn btn-warning", :style => "color: #ffffff" %>
<%else%>
<blockquote>
  <p class="text-danger">Nie masz wystarczających uprawnień do podglądu tej strony</p>
</blockquote>
<% end %>
</div>