config/routes.rb
Rails.application.routes.draw do

  resources :book_histories
  get 'homes/new'
  get 'homes/show' => 'homes#show', as: :home
  get 'sessions/signup' => 'sessions#signup', :as => :signup
  post 'sessions/new_user' => 'sessions#new_user'
  root :to => 'sessions#new'
  get    'login'   => 'sessions#new', :as => :loginpage
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

   get 'books/:id/borrow' => 'books#borrow', :as => :borrow_book
   get 'book_histories/:data/index' => 'book_histories#index', :as =>:check_user_history
   get 'books/:id/request' => 'books#request_book', :as => :request_book
   get 'books/:id/return' => 'books#return', :as => :return_book
   get 'books/:id/cancel_request' => 'books#cancel_request', :as => :cancel_request_book
  resources :searches
  resources :books
  resources :users

  match ':controller(/:action(/:id))', :via=> :get

end

app/models/book.rb
class Book < ActiveRecord::Base
	belongs_to :user
	has_many :book_histories
  validates :title,
            :presence => {:message => "Wpisz tytuł"},
            :length => {:maximum => 100}
  validates :author,
            :presence => {:message => "Wpisz autora"},
            :length => {:maximum => 100}
  validates :description,
            :presence => {:message => "Dodaj opis"},
            :length => {:maximum => 500}
  validates :isbn,
            :presence => {:message => "Wpisz ISBN"},
            :uniqueness => true,
            :length => {:minimum => 13, :maximum => 13},
            :numericality => {:only_integer => true }
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  #User Defined
  def borrow
    @book=Book.find(params[:id])
    Rails.logger = Logger.new(STDOUT)
    logger.debug "Id książki: #{params[:id]}"
    logger.debug "Książka zwrócona przez wyszukiwanie: #{@book.id}"
    @book.is_borrowed=true
    @book.user_id = session[:user_id]

    if @book.save!
      # redirect_to @book, notice: 'Book was successfully borrowed.'
      render :show, status: :ok, location: @book
    else
      render :show
      # render json: @book.errors, status: :unprocessable_entity
    end
    #create check_out_history of book #vicky
    create_book_history params[:id], session[:user_id],Time.now.getlocal
  end

  def create_book_history(book_id, user_id, chk_out_dt)
    @book_history = BookHistory.new
    @book_history.book_id = book_id
    @book_history.user_id = user_id
    @book_history.chk_out_dt = chk_out_dt
    @book_history.save!
  end

  def return
    @book=Book.find(params[:id])
    Rails.logger = Logger.new(STDOUT)
    logger.debug "Id książki: #{params[:id]}"
    logger.debug "Książka zwrócona przez wyszukiwanie: #{@book.id}"
    invalid_return = false
    if @book.is_borrowed && (@book.user_id != @current_user.id)
      invalid_return = true
    end
    send_mail = false
    if @book.is_requested
      user = User.find(@book.requested_by)
      send_mail = true
    end
    @book.is_borrowed=false
    @book.user_id = nil
    @book.requested_by = nil
    @book.is_requested = false
    if !invalid_return && @book.save!
      # redirect_to @book, notice: 'Book was successfully borrowed.'
      render :show, status: :ok, location: @book
    else
      flash.now[:danger] = "Nieprawidłowa operacja!"
      render :show     #render json: @book.errors, status: :unprocessable_entity
    end
    #create check_out_history of book #vicky #add check in date
    if send_mail
      send_email_to_requester(user, @book.title)
    end
    complete_book_history params[:id],session[:user_id],Time.now.getlocal
  end

  def send_email_to_requester(user, book_name)
    Notifier.send_notification(user.email, user.name, book_name).deliver_now!
  end

  def complete_book_history(book_id, user_id, chk_in_dt)
    @book_history = BookHistory.find_by(:book_id => book_id, :user_id => user_id, :chk_in_date => nil)
    if @book_history
      @book_history.chk_in_date = chk_in_dt
      @book_history.save!
    end
  end

  def request_book
    @book=Book.find(params[:id])
    @book.is_requested=true
    @book.requested_by=session[:user_id]
    if @book.save!
     render :show, status: :ok, location: @book
    else
    render :show
    render json: @book.errors, status: :unprocessable_entity
    end
  end

  def cancel_request
    @book=Book.find(params[:id])
    @book.is_requested=false
    @book.requested_by=nil
    if @book.save!
     render :show, status: :ok, location: @book
    else
    render :show
    render json: @book.errors, status: :unprocessable_entity
    end
  end

  # GET /books
  # GET /books.json
  def index
    @books = Book.paginate_by_sql("select * from books where is_deleted = 'f'", :page => params[:page], :per_page => 10)
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find(params[:id])
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)
    Rails.logger = Logger.new(STDOUT)
    logger.debug "Parametry zapisane jako #{book_params}"
    @book.is_deleted = false

    respond_to do |format|
      if @book.save
        logger.debug "Książka zapisana z id #{@book.id}"
        format.html { redirect_to @book, notice: 'Książka została dodana' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    @book = Book.find(params[:id])
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Książka została zaktualizowana.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book = Book.delete(params[:id])
    respond_to do |format|
        format.html { redirect_to books_url, notice: 'Książka została usunięta' }
        format.json { head :no_content }
    end
  end

    # Use callbacks to share common setup or constraints between actions.
  def set_book
    @book = Book.find(params[:id])
  end

private
    # Never trust parameters from the scary internet, only allow the white list through.
  def book_params
    params.require(:book).permit(:title, :description, :author, :isbn, :is_borrowed, :is_deleted)
  end

  end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> Ta książka jest zablokowana:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title, "Tytuł" %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description, "Opis" %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :author, "Autor" %><br>
    <%= f.text_field :author %>
  </div>
    <div class="field">
    <%= f.label :isbn %><br>
    <%= f.text_field :isbn %>
  </div>

  <div class="actions">
    <%= f.submit "Zastosuj", :class => "btn btn-success", :style => "color: #ffffff" %>
  </div>
<% end %>

app/views/books/_form_edit.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> Ta książka jest zablokowana:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title, "Tytuł" %><br>
    <%= f.text_field :title, class: "form-control"%>
  </div>
  <div class="field">
    <%= f.label :description, "Opis" %><br>
    <%= f.text_field :description, class: "form-control"%>
  </div>
  <div class="field">
    <%= f.label :author, "Autor" %><br>
    <%= f.text_field :author, class: "form-control"%>
  </div>

  <div class="actions">
    <%= f.submit "Zastosuj", :class => "btn btn-success", :style => "color: #ffffff" %>
  </div>
<% end %>

app/views/books/edit.html.erb
<div style="margin:0 auto; left:0px; padding:5px 55px 5px 55px">
<% if @current_user.is_admin %>
<h3>Edycja książki</h3>

<%= render 'form_edit' %>

<%= link_to 'Powrót', books_path, :class => "btn btn-primary", :style => "color: #ffffff" %>
<%else%>
<blockquote>
	<p class="text-danger">Nie masz wystarczających uprawnień do podglądu tej strony.</p>
</blockquote>
<% end %>
</div>

app/views/books/index.html.erb
<div style="margin:0 auto; left:0px; padding:5px 25px 5px 25px">
 <p id="notice"><%= notice %></p>

  <p class="lead">Wszystkie książki</p>
    <table class="table"style="max-width:1366px">
      <thead>
        <tr style="background-color:#D5DBDB">
          <th>Tytuł</th>
          <th style="min-width:300px;">Opis</th>
          <th>Autor</th>
          <th>Isbn</th>
          <th>Status</th>
          <%if @current_user.is_admin %>
          <th>Zarezerwowana przez </th>
          <%end%>
          <th colspan="5"></th>
        </tr>
      </thead>
      <% @books.each do |book| %>
      <tbody>
        <tr>
          <td><%= book.title %></td>
          <td><%= book.description %></td>
          <td><%= book.author %></td>
          <td><%= book.isbn %></td>
          <% if book.is_borrowed %>
          <td><span class="label label-danger">Zarezerwowana</span></td>
          <% else %>
          <td><span class="label label-success">Dostępna</span></td>
          <%end%>
          <% if book.is_borrowed && @current_user.is_admin %>
          <%@user = User.find(book.user_id)%>
          <td><%=@user.name%> (<%=@user.email %>)</td>
          <%else%>
          <td></td>
          <%end%>
          <td><%= link_to 'Pokaż', book, :class => "btn btn-primary", :style => "color: #ffffff; font-size:12px;" %></td>
          <%if @current_user.is_admin? %>
              <td><%=link_to 'Historia rezerwacji', check_user_history_path(:data => {:user_id => nil, :book_id => book.id}), :class => "btn btn-success", :style => "color: #ffffff;font-size:12px;"%></td>
          <td><%= link_to 'Edytuj', edit_book_path(book), :class => "btn btn-warning", :style => "color: #ffffff;font-size:12px;" %></td>
          <%if !book.is_borrowed %>
          <td><%= link_to 'Usuń', book, method: :delete, data: { confirm: 'Czy jesteś pewien?' }, :class => "btn btn-danger", :style => "color: #ffffff;font-size:12px;" %></td>
          <%else%><td></td>
          <%end%>
          <%end%>
          <%if book.is_borrowed %>

          <% if book.user_id == @current_user.id %>

          <td><%= link_to 'Zwróć', return_book_path(:id => book.id), :class => "btn btn-warning", :style => "color: #ffffff;font-size:12px;"%></td>
          <%else%>
          <% if !book.is_requested %>
          <td><%= link_to 'Prośba o powiadomienie', request_book_path(:id => book.id), :class => "btn btn-warning", :style => "color: #ffffff;font-size:12px;"%></td>
          <%else%>
          <% if book.is_requested && (book.requested_by == @current_user.id) %>          
          <td><%= link_to 'Anuluj powiadomienia', cancel_request_book_path(:id => book.id), :class => "btn btn-warning", :style => "color: #ffffff;font-size:12px;"%></td>
          <%end%>
          <%end%>
          <%end%>
          <%else%>
          <td><%=link_to 'Zarezerwuj', borrow_book_path(:id => book.id), :class => "btn btn-success", :style => "color: #ffffff;font-size:12px;"%></td>
          <%end%>
          <%end%>
        </tr>
      </tbody>
    </table>
    <%= will_paginate @books%>
    <br>
    <br><br><br><br>
    <%if @current_user.is_admin %>
    <%= link_to 'Dodaj książkę', new_book_path, :class => "btn btn-success", :style => "color: #ffffff" %>
    <% end %>

app/views/books/new.html.erb
<div style="margin:0 auto; left:0px; padding:5px 55px 5px 55px">
<h3>Nowa książka</h3>

<%= render 'form' %>

<%= link_to 'Powrót', books_path, :class => "btn btn-info", :style => "color: #ffffff"%>
</div>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<table class="table" style="max-width:1366px">
  <thead>
    <tr>
      <th><strong>Tytuł</strong></th>
      <th><strong>Opis</strong></th>
      <th><strong>Autor</strong></th>
      <th><strong>Isbn</strong></th>
      <th><strong>Status</strong></th>
    </tr>
  </thead>
  <tbody>

    <tr>
      <td><%= @book.title %></td>
      <td><%= @book.description %></td>
      <td><%= @book.author %></td>
      <td><%= @book.isbn %></td>
      <% if @book.is_borrowed %>
      <td><span class="label label-danger">Zarezerwowana</span></td>
      <%else%>
      <td><span class="label label-success">Dostępna</span></td>
      <%end%>
    </table>

    <%if @current_user.is_admin %>
    <%= link_to 'Edycja', edit_book_path(@book), :class => "btn btn-danger", :style => "color: #ffffff" %> | 
    <%end%>
    <%= link_to 'Powrót', books_path, :class => "btn btn-warning", :style => "color: #ffffff" %>