config/routes.rb
Rails.application.routes.draw do

  resources :book_histories
  get 'homes/new'
  get 'homes/show' => 'homes#show', as: :home
  get 'sessions/signup' => 'sessions#signup', :as => :signup
  post 'sessions/new_user' => 'sessions#new_user'
  root :to => 'sessions#new'
  get    'login'   => 'sessions#new', :as => :loginpage
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

   get 'books/:id/borrow' => 'books#borrow', :as => :borrow_book
   get 'book_histories/:data/index' => 'book_histories#index', :as =>:check_user_history
   get 'books/:id/request' => 'books#request_book', :as => :request_book
   get 'books/:id/return' => 'books#return', :as => :return_book
   get 'books/:id/cancel_request' => 'books#cancel_request', :as => :cancel_request_book
  resources :searches
  resources :books
  resources :users

  match ':controller(/:action(/:id))', :via=> :get

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Biblioteka</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<style>
@import url('https://fonts.googleapis.com/css?family=Open+Sans');
.btn:hover{
background-color:#1B2631 !important;
}
.str {
  color: #ffffff;
  font-size: 14px;
  background-color: #138D75;
  -webkit-border-radius: 3px;
  -moz-border-radius: 3px;
  border-radius: 3px;
  border:none;
  }
.str: hover {
  color: #ffffff;
  background-color: #1B2631 !important;
  }
  
.btn-xlg {
  font-size: 14px;
  background-color: #5D6D7E;
  -webkit-border-radius: 3px;
  -moz-border-radius: 3px;
  border-radius: 3px;
  border:none;
}

.btn-xlg: hover {
  color: #fff;
  background-color: #2E86C1 !important;
  }
  
li {
padding:6px;
}

.animate {
  -webkit-animation: animatezoom 0.2s;
  animation: animatezoom 0.2s;
}

@keyframes animatezoom {
  from {transform: scale(0)} 
  to {transform: scale(1)}
}
</style>
</head>
<body>
  <header class="navbar navbar-fixed-top navbar-inverse" style="background-color: #2E4053; padding:10px 0px 10px 0px">
    <div class="container">
      <nav>
        <% if logged_in? %>
        <ul class="nav navbar-nav navbar-left">
		<li style="margin-right:10px;"><%=image_tag("biblioteka_books.png")%></li>
          <li style="float: left">
            <%= link_to "Strona główna", home_path, class: "btn str", style: "color: #ffffff"%>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li>
            <%= link_to "Wyszukiwanie książek", new_search_path, class: "btn btn-xlg" , style: "color: #ffffff"%>
          </li>
          <li >
            <%= link_to "Wszystkie książki", books_path, class: "btn btn-xlg", style: "color: #ffffff;"%>
          </li>
          <li>
            <%= link_to "Historia rezerwacji", check_user_history_path(:data => {:user_id => @current_user.id, :book_id => nil}), class: "btn btn-xlg", style: "color: #ffffff"%>
          </li>
		   <li style="float: left">
            <li style="margin:16px 5px 16px 36px;color: #ffffff;font-size: 14px"> Witaj, <%=@current_user.name %>! </li>
          </li>
		  <li style="margin-right:4px;"><%=image_tag("avatar.png")%></li>
          <li>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="color: #ffffff">
              <b class="caret" style="border-top:9px solid #ffffff"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Pokaż profil", user_path(@current_user.id) %></li>
              <li><%= link_to "Edytuj profil", edit_user_path(@current_user.id) %></li>
              <% if @current_user.is_admin %>
              <li><%= link_to "Zarządzanie użytkownikami", users_path%></li>
              <li><%= link_to "Zarządzanie książkami", books_path%></li>
              <% end %>
              <li><%= link_to "Edytuj profil", edit_user_path(@current_user.id) %></li>
              <li class="divider"></li>
              <li><%= link_to '<i class="glyphicon glyphicon-off"></i> Wyloguj'.html_safe, logout_path, method: :delete, :style => "float: left" %></li>
            </ul>
          </li>
        </ul>
      <% end %>
      </nav>
    </div>
  </header>
  <br/><br/>
  <% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
  <div class="container animate" style="width:max-content; background-color: white; margin: auto; left:0px; padding:20px 15px 20px 15px;background-color: rgb(255,255,255); background-color: rgba(255,255,255,0.85); border-radius: 8px">
    <%= yield %>
  </div>
  <br/>
  <br/>

</body>
</html>